### ISSUE TITLE
Running example of importFromJson

### ISSUE THREAD

**Issue by programando-ideas** [jepiqueau/capacitor-sqlite#17] opened 2020-05-11 22:53 UTC
Hello! Could someone help me with a functional example of the importFromJson function.

I get this error "importFromJson command failed: Stringify Json Object not Valid"

please help!!!

thanks!

**Comment by jepiqueau** [comment] 2020-05-12 05:21
@programando-ideas First thank to use the plugin. Did you have a look at ```https://github.com/jepiqueau/angular-sqlite-app-starter``` you have an example of importFromJson  in https://github.com/jepiqueau/angular-sqlite-app-starter/blob/master/src/app/testsqlite/testsqlite.component.ts line 365. 
Do not hesitate to come back if you have more questions about it

**Comment by programando-ideas** [comment] 2020-05-12 21:32
Hello! Thank you so much for your answer.

Just a few comments:

1) It's very important to note in the documentation that the parameter must be passed to the function **importFromJson**  as follows
 ```
 const js = JSON.stringify (dataToImport)
 importFromJson ({jsonstring: js})
 ```
otherwise it doesn't work!

2) The table schema must contain a column named id of the integer type
```
 schema: [
            { column: 'id', value: 'INTEGER PRIMARY KEY NOT NULL' }
```
otherwise it doesn't work!

3) Thanks very much for your example!!!!

greetingsss!!

**Comment by jepiqueau** [comment] 2020-05-13 05:23
@programando-ideas  Thanks for your remarks
- 1) this is written in the doc  
`### importFomJson({jsonstring:fooJSONString}) => Promise<{changes:{changes:number},message:string}>`
-2) agree i will add it

**Comment by jepiqueau** [comment] 2020-05-13 05:44
@programando-ideas Done

**Comment by programando-ideas** [comment] 2020-05-13 17:29
One more thing, the following example when I run it on an Android emulator gives an error

```
      let users = [];
      let is = '';

      for (let index = 0; index < 1000; index++) {
        is = index.toString();
        users.push([
          index,
          'name ' + is,
          'surname' + is,
          Math.floor(Math.random() * (80 - 20)) + 20,
          new Date().getTime() / 1000 | 0
        ]);
      }
      const dataToImport: any = {
        database: 'db-from-json',
        encrypted: false,
        mode: 'full',
        tables: [
          {
            name: 'users',
            schema: [
              { column: 'id', value: 'INTEGER PRIMARY KEY NOT NULL' },
              { column: 'email', value: 'TEXT UNIQUE NOT NULL' },
              { column: 'name', value: 'TEXT' },
              { column: 'age', value: 'INTEGER' },
              { column: 'last_modified', value: 'INTEGER' }
            ],
            indexes: [
              { name: 'index_user_on_name', column: 'name' },
              { name: 'index_user_on_last_modified', column: 'last_modified' }
            ],
            values: users
          }]
      };

      const result: any = await this._SQLiteService.importFromJson(JSON.stringify(dataToImport));
      console.log('import result ', result)
```
![error](https://user-images.githubusercontent.com/54816242/81844622-f9bcb580-9514-11ea-8024-d3428cfb29f8.PNG)

`unable to close due to unfinalized statements or unfinished backups: sqlite3_close() failed`

This error only occurs when you want to insert many records, with few they do not occur. In this example I want to insert **1000 records**.

Thank you very much for your support!!

**Comment by fernandocode** [comment] 2020-05-13 17:53
> One more thing, the following example when I run it on an Android emulator gives an error
> 
> ```
>       let users = [];
>       let is = '';
> 
>       for (let index = 0; index < 1000; index++) {
>         is = index.toString();
>         users.push([
>           index,
>           'name ' + is,
>           'surname' + is,
>           Math.floor(Math.random() * (80 - 20)) + 20,
>           new Date().getTime() / 1000 | 0
>         ]);
>       }
>       const dataToImport: any = {
>         database: 'db-from-json',
>         encrypted: false,
>         mode: 'full',
>         tables: [
>           {
>             name: 'users',
>             schema: [
>               { column: 'id', value: 'INTEGER PRIMARY KEY NOT NULL' },
>               { column: 'email', value: 'TEXT UNIQUE NOT NULL' },
>               { column: 'name', value: 'TEXT' },
>               { column: 'age', value: 'INTEGER' },
>               { column: 'last_modified', value: 'INTEGER' }
>             ],
>             indexes: [
>               { name: 'index_user_on_name', column: 'name' },
>               { name: 'index_user_on_last_modified', column: 'last_modified' }
>             ],
>             values: users
>           }]
>       };
> 
>       const result: any = await this._SQLiteService.importFromJson(JSON.stringify(dataToImport));
>       console.log('import result ', result)
> ```
> 
> ![error](https://user-images.githubusercontent.com/54816242/81844622-f9bcb580-9514-11ea-8024-d3428cfb29f8.PNG)
> 
> `unable to close due to unfinalized statements or unfinished backups: sqlite3_close() failed`
> 
> This error only occurs when you want to insert many records, with few they do not occur. In this example I want to insert **1000 records**.
> 
> Thank you very much for your support!!

Not specifically about this library, but as you mentioned that this only occurs with a large flow of information (1000 records) I believe it is related to the problem of OutOfMemory on Android, with the deserialization of JSON there (or in the transfer between javascript and the Native), as this consumes a lot of memory, I recommend you do it in parts.

A way to seek to identify this, and track the memory in the development tools of Android Studio, and even check the Trace of the error there in Nativo.

I am quoting this because it has already occurred to me by sending very large commands at once, which caused OutOfMemory on weaker devices. (but that was with "cordova-sqlite-storage")

The idea is just to indicate something to investigate. Update us if you can verify this.

**Comment by jepiqueau** [comment] 2020-05-14 08:07
@programando-ideas @fernandocode Well, i have reproduce the issue, its happened randomly meaning not at the same insert command of a user. 
It is a message send by `sqlcipher compilestatement` .
if you look at the database, all users have been created. I will have a look if i can override this message

**Comment by jepiqueau** [comment] 2020-05-14 09:31
@programando-ideas @fernandocode i update sqlcipher to 4.4.0 so the random error does not exist anymore but it is still failing as it try to close the db while the endTransaction is not completed. i have tried to create a synchronized block but it does not change anything. Any ideas from your side ?

**Comment by jepiqueau** [comment] 2020-05-14 10:42
@programando-ideas @fernandocode i published a new release capacitor-sqlite@2.1.0-3 where the problem is fixed. for the time being i remove the db.close(). Any suggestion is welcome

**Comment by programando-ideas** [comment] 2020-05-14 13:50
Hello!!, sorry for not responding sooner. Thank you very much for the new version :)

It's true, the library save the date successfully beyond the error occurs.

I'll download the new version for testing. I'll notify to you if and error occur.

Thanks!!!

**Comment by programando-ideas** [comment] 2020-05-14 14:10
@jepiqueau @fernandocode  I leave you the result of the tests with 2500 records! Everything worked perfect!

### package.json
&nbsp;&nbsp;&nbsp;&nbsp;![packagejson](https://user-images.githubusercontent.com/54816242/81944176-ffbca000-95c1-11ea-80d4-25cc482a31fb.png)

### Android emulator hardware
&nbsp;&nbsp;&nbsp;&nbsp;![android_emulator_hardware](https://user-images.githubusercontent.com/54816242/81944183-021efa00-95c2-11ea-8065-a6228c5b54e4.PNG)

### Console output
&nbsp;&nbsp;&nbsp;&nbsp;![test_result_1](https://user-images.githubusercontent.com/54816242/81944194-05b28100-95c2-11ea-8b69-29dd2eb80bc4.PNG)

### Database SQLite in device after call importFromJson
&nbsp;&nbsp;&nbsp;&nbsp;![test_result_2](https://user-images.githubusercontent.com/54816242/81944201-077c4480-95c2-11ea-8ed8-203115a35eb5.PNG)

thanksss!!

**Comment by jepiqueau** [comment] 2020-05-14 18:02
@programando-ideas 
You are welcome. i close the issue

**Closed by jepiqueau** 2020-05-14 18:02 UTC
